export const CORNER_LIGHTS_PANEL_STYLES = {
  body: {
    display: 'flex',
    flexDirection: 'column' as const,
    gap: '4px',
    overflowY: 'auto' as const,
    padding: '8px',
  },
  card: {
    borderRadius: '8px',
    display: 'flex',
    flexDirection: 'column' as const,
    gap: '8px',
    padding: '8px 10px',
  },
  cardActive: {
    background: 'rgba(255,255,255,0.04)',
    border: '1px solid rgba(255,255,255,0.08)',
  },
  cardHeader: {
    alignItems: 'center',
    display: 'flex',
    justifyContent: 'space-between',
  },
  cardInactive: {
    background: 'transparent',
    border: '1px solid rgba(255,255,255,0.04)',
  },
  fieldGroup: {
    display: 'flex',
    flexDirection: 'column' as const,
    gap: '3px',
  },
  fieldLabel: {
    color: 'rgba(255,255,255,0.35)',
    fontSize: '9px',
    letterSpacing: '0.07em',
    textTransform: 'uppercase' as const,
  },
  header: {
    alignItems: 'center',
    borderBottom: '1px solid rgba(255,255,255,0.07)',
    display: 'flex',
    justifyContent: 'space-between',
    padding: '10px 12px',
  },
  headerActions: {
    display: 'flex',
    gap: '6px',
  },
  helperRow: {
    alignItems: 'center',
    display: 'flex',
    gap: '5px',
  },
  iconBtn: {
    alignItems: 'center',
    background: 'transparent',
    border: '1px solid rgba(255,255,255,0.1)',
    borderRadius: '6px',
    color: 'rgba(255,255,255,0.5)',
    cursor: 'pointer',
    display: 'flex',
    fontSize: '11px',
    justifyContent: 'center',
    padding: '4px 8px',
  },
  input: {
    background: 'rgba(255,255,255,0.05)',
    border: '1px solid rgba(255,255,255,0.08)',
    borderRadius: '6px',
    boxSizing: 'border-box' as const,
    color: '#e8edf4',
    fontSize: '11px',
    padding: '4px 6px',
    width: '100%',
  },
  intensityRow: {
    alignItems: 'center',
    display: 'grid',
    gap: '6px',
    gridTemplateColumns: '1fr 52px',
  },
  intensitySlider: {
    accentColor: '#4f8ef7',
    cursor: 'pointer',
    width: '100%',
  },
  lightName: {
    color: '#e8edf4',
    fontSize: '12px',
    fontWeight: 600,
  },
  lightNameDisabled: {
    color: 'rgba(255,255,255,0.3)',
    fontSize: '12px',
    fontWeight: 600,
  },
  panel: {
    backdropFilter: 'blur(20px)',
    background: 'rgba(12, 14, 20, 0.88)',
    border: '1px solid rgba(255,255,255,0.08)',
    borderRadius: '12px',
    boxShadow: '0 8px 32px rgba(0,0,0,0.4)',
    color: '#e8edf4',
    display: 'flex',
    flexDirection: 'column',
    left: '12px',
    maxHeight: '70vh',
    overflow: 'hidden',
    position: 'fixed' as const,
    top: '60%',
    transform: 'translateY(-50%)',
    width: '260px',
    zIndex: 40,
  },
  row: {
    alignItems: 'center',
    display: 'grid',
    gap: '6px',
    gridTemplateColumns: '1fr 1fr 1fr',
  },
  title: {
    color: 'rgba(255,255,255,0.5)',
    fontSize: '12px',
    fontWeight: 600,
    letterSpacing: '0.08em',
    textTransform: 'uppercase' as const,
  },
  toggle: {
    alignItems: 'center',
    cursor: 'pointer',
    display: 'flex',
    gap: '5px',
  },
  toggleLabel: {
    color: 'rgba(255,255,255,0.4)',
    fontSize: '10px',
    letterSpacing: '0.06em',
    textTransform: 'uppercase' as const,
  },
} as const;
