#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

branch=$(git branch --show-current)

if [ "$branch" = "main" ] || [ "$branch" = "staging" ]; then
  echo "Direct commits to $branch are not allowed."
  exit 1
fi

npx lint-staged
